version: "3"

services:
  butler-brain:
    build: https://github.com/Schetsboek/butler-brain.git
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 10001:10001

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../mongo:/data/db
